// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Covid struct {
	ID             string `json:"id"`
	Dailyconfirmed string `json:"dailyconfirmed"`
	Dailydeceased  string `json:"dailydeceased"`
	Dailyrecovered string `json:"dailyrecovered"`
	Date           string `json:"date"`
	Dateymd        string `json:"dateymd"`
	Totalconfirmed string `json:"totalconfirmed"`
	Totaldeceased  string `json:"totaldeceased"`
	Totalrecovered string `json:"totalrecovered"`
}

type Covid10 struct {
	Cursor string `json:"cursor"`
	Covid  *Covid `json:"covid"`
}

type Covid1 struct {
	Dailyconfirmed *string `json:"dailyconfirmed"`
	Dailydeceased  *string `json:"dailydeceased"`
	Dailyrecovered *string `json:"dailyrecovered"`
	Date           *string `json:"date"`
	Dateymd        *string `json:"dateymd"`
	Totalconfirmed *string `json:"totalconfirmed"`
	Totaldeceased  *string `json:"totaldeceased"`
	Totalrecovered *string `json:"totalrecovered"`
}

type Covid2 struct {
	Dailyconfirmed *string `json:"dailyconfirmed"`
	Dailydeceased  *string `json:"dailydeceased"`
	Dailyrecovered *string `json:"dailyrecovered"`
	Date           *string `json:"date"`
	Dateymd        *string `json:"dateymd"`
	Totalconfirmed *string `json:"totalconfirmed"`
	Totaldeceased  *string `json:"totaldeceased"`
	Totalrecovered *string `json:"totalrecovered"`
}

type CovidMain struct {
	CasesTimeSeries []*Covid  `json:"cases_time_series"`
	Statewise       []*Covid1 `json:"statewise"`
	Tested          []*Covid2 `json:"tested"`
}

type Covids struct {
	Covids   []*Covid10 `json:"covids"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type Ips struct {
	IPType  string `json:"ipType"`
	IP      string `json:"ip"`
	Netmask string `json:"netmask"`
	Gateway string `json:"gateway"`
}

type NewIps struct {
	IPType  string `json:"ipType"`
	IP      string `json:"ip"`
	Netmask string `json:"netmask"`
	Gateway string `json:"gateway"`
}

type NewNode struct {
	IP          string      `json:"ip"`
	Serial      string      `json:"serial"`
	Model       string      `json:"model"`
	Credentials string      `json:"credentials"`
	Template    string      `json:"template"`
	Networks    []*NewIps   `json:"networks"`
	Roles       []*NewRoles `json:"roles"`
}

type NewRoles struct {
	RoleType string    `json:"roleType"`
	Label    []*string `json:"label"`
}

type Node struct {
	IP          string   `json:"ip"`
	Serial      string   `json:"serial"`
	Model       string   `json:"model"`
	Credentials string   `json:"credentials"`
	Template    string   `json:"template"`
	Networks    []*Ips   `json:"networks"`
	Roles       []*Roles `json:"roles"`
}

type Node1 struct {
	Cursor string `json:"cursor"`
	Node   *Node  `json:"node"`
}

type Nodes struct {
	Nodes    []*Node1  `json:"nodes"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage *bool  `json:"hasNextPage"`
}

type Roles struct {
	RoleType string    `json:"roleType"`
	Label    []*string `json:"label"`
}
