// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Covid struct {
	ID             string `json:"id"`
	Dailyconfirmed string `json:"dailyconfirmed"`
	Dailydeceased  string `json:"dailydeceased"`
	Dailyrecovered string `json:"dailyrecovered"`
	Date           string `json:"date"`
	Dateymd        string `json:"dateymd"`
	Totalconfirmed string `json:"totalconfirmed"`
	Totaldeceased  string `json:"totaldeceased"`
	Totalrecovered string `json:"totalrecovered"`
}

type Covid10 struct {
	Cursor string `json:"cursor"`
	Covid  *Covid `json:"covid"`
}

type CovidDataSort struct {
	Dailyconfirmed *Sort `json:"dailyconfirmed"`
	Dailydeceased  *Sort `json:"dailydeceased"`
	Dailyrecovered *Sort `json:"dailyrecovered"`
	Date           *Sort `json:"date"`
	Totalconfirmed *Sort `json:"totalconfirmed"`
	Totaldeceased  *Sort `json:"totaldeceased"`
	Totalrecovered *Sort `json:"totalrecovered"`
}

type Covid1 struct {
	Dailyconfirmed *string `json:"dailyconfirmed"`
	Dailydeceased  *string `json:"dailydeceased"`
	Dailyrecovered *string `json:"dailyrecovered"`
	Date           *string `json:"date"`
	Dateymd        *string `json:"dateymd"`
	Totalconfirmed *string `json:"totalconfirmed"`
	Totaldeceased  *string `json:"totaldeceased"`
	Totalrecovered *string `json:"totalrecovered"`
}

type Covid2 struct {
	Dailyconfirmed *string `json:"dailyconfirmed"`
	Dailydeceased  *string `json:"dailydeceased"`
	Dailyrecovered *string `json:"dailyrecovered"`
	Date           *string `json:"date"`
	Dateymd        *string `json:"dateymd"`
	Totalconfirmed *string `json:"totalconfirmed"`
	Totaldeceased  *string `json:"totaldeceased"`
	Totalrecovered *string `json:"totalrecovered"`
}

type CovidMain struct {
	CasesTimeSeries []*Covid  `json:"cases_time_series"`
	Statewise       []*Covid1 `json:"statewise"`
	Tested          []*Covid2 `json:"tested"`
}

type Covids struct {
	Covids   []*Covid10 `json:"covids"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type Ips struct {
	IPType  string `json:"ipType"`
	IP      string `json:"ip"`
	Netmask string `json:"netmask"`
	Gateway string `json:"gateway"`
}

type NewIps struct {
	IPType  string `json:"ipType"`
	IP      string `json:"ip"`
	Netmask string `json:"netmask"`
	Gateway string `json:"gateway"`
}

type NewNode struct {
	IP          string      `json:"ip"`
	Serial      string      `json:"serial"`
	Model       string      `json:"model"`
	Credentials string      `json:"credentials"`
	Template    string      `json:"template"`
	Networks    []*NewIps   `json:"networks"`
	Roles       []*NewRoles `json:"roles"`
}

type NewRoles struct {
	RoleType string    `json:"roleType"`
	Label    []*string `json:"label"`
}

type Node struct {
	IP          string   `json:"ip"`
	Serial      string   `json:"serial"`
	Model       string   `json:"model"`
	Credentials string   `json:"credentials"`
	Template    string   `json:"template"`
	Networks    []*Ips   `json:"networks"`
	Roles       []*Roles `json:"roles"`
}

type Node1 struct {
	Cursor string `json:"cursor"`
	Node   *Node  `json:"node"`
}

type Nodes struct {
	Nodes    []*Node1  `json:"nodes"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage *bool  `json:"hasNextPage"`
}

type Roles struct {
	RoleType string    `json:"roleType"`
	Label    []*string `json:"label"`
}

type Sort string

const (
	SortAsc  Sort = "asc"
	SortDesc Sort = "desc"
)

var AllSort = []Sort{
	SortAsc,
	SortDesc,
}

func (e Sort) IsValid() bool {
	switch e {
	case SortAsc, SortDesc:
		return true
	}
	return false
}

func (e Sort) String() string {
	return string(e)
}

func (e *Sort) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Sort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Sort", str)
	}
	return nil
}

func (e Sort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
